
import { Translation, Language } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  ar: {
    title: 'مولد رموز QR المطور',
    subtitle: 'أنشئ رموز QR احترافية بسهولة تامة',
    link: 'رابط (URL)',
    text: 'نص',
    wifi: 'واي فاي',
    email: 'بريد إلكتروني',
    call: 'اتصال',
    sms: 'رسالة SMS',
    vcard: 'جهة اتصال',
    data: 'بيانات الرمز',
    design: 'تخصيص التصميم',
    fgColor: 'لون الرمز',
    bgColor: 'لون الخلفية',
    removeMargin: 'إزالة الإطار الأبيض',
    downloadQuality: 'جودة التحميل',
    downloadBtn: 'تحميل الرمز (PNG)',
    placeholderUrl: 'https://example.com',
    placeholderText: 'اكتب نصك هنا...',
    placeholderPhone: '05xxxxxxxx',
    ssid: 'اسم الشبكة (SSID)',
    password: 'كلمة المرور',
    encryption: 'نوع التشفير',
    subject: 'الموضوع',
    body: 'نص الرسالة',
    firstName: 'الاسم الأول',
    lastName: 'اللقب',
    org: 'الشركة / المنظمة',
    low: 'منخفضة (512px)',
    high: 'عالية (1024px)',
    ultra: 'فائقة (2048px)',
    max: 'قصوى (4096px)',
    livePreview: 'معاينة مباشرة',
    lightMode: 'وضع النهار',
    darkMode: 'وضع الليل'
  },
  en: {
    title: 'Advanced QR Generator',
    subtitle: 'Create professional QR codes with ease',
    link: 'Link (URL)',
    text: 'Text',
    wifi: 'Wi-Fi',
    email: 'Email',
    call: 'Call',
    sms: 'SMS',
    vcard: 'V-Card',
    data: 'Code Data',
    design: 'Design Customization',
    fgColor: 'QR Color',
    bgColor: 'Background Color',
    removeMargin: 'Remove White Border',
    downloadQuality: 'Download Quality',
    downloadBtn: 'Download QR (PNG)',
    placeholderUrl: 'https://example.com',
    placeholderText: 'Type your text here...',
    placeholderPhone: '+123456789',
    ssid: 'Network Name (SSID)',
    password: 'Password',
    encryption: 'Encryption',
    subject: 'Subject',
    body: 'Message Body',
    firstName: 'First Name',
    lastName: 'Last Name',
    org: 'Organization',
    low: 'Low (512px)',
    high: 'High (1024px)',
    ultra: 'Ultra (2048px)',
    max: 'Max (4096px)',
    livePreview: 'Live Preview',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode'
  }
};
