
import { Translation, Language } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  ar: {
    title: 'منصة الباركود العالمية',
    subtitle: 'أقوى أداة ويب مجانية لإنشاء كافة أنواع الرموز والباركود',
    qrTool: 'مولد رموز QR المطور',
    barcodeTool: 'مولد الباركود الاحترافي',
    selectTool: 'اختر الخدمة المطلوبة',
    link: 'رابط (URL)',
    text: 'نص',
    wifi: 'واي فاي',
    email: 'بريد إلكتروني',
    call: 'اتصال',
    sms: 'رسالة SMS',
    vcard: 'جهة اتصال',
    data: 'بيانات الرمز',
    design: 'تخصيص التصميم',
    fgColor: 'لون الرمز',
    bgColor: 'لون الخلفية',
    removeMargin: 'إزالة الإطار الأبيض',
    downloadQuality: 'جودة التحميل',
    downloadBtn: 'تحميل الرمز (PNG)',
    placeholderUrl: 'https://example.com',
    placeholderText: 'اكتب نصك هنا...',
    placeholderPhone: '05xxxxxxxx',
    ssid: 'اسم الشبكة (SSID)',
    password: 'كلمة المرور',
    encryption: 'نوع التشفير',
    subject: 'الموضوع',
    body: 'نص الرسالة',
    firstName: 'الاسم الأول',
    lastName: 'اللقب',
    org: 'الشركة / المنظمة',
    low: 'منخفضة (512px)',
    high: 'عالية (1024px)',
    ultra: 'فائقة (2048px)',
    max: 'قصوى (4096px)',
    livePreview: 'معاينة مباشرة',
    lightMode: 'وضع النهار',
    darkMode: 'وضع الليل',
    barcodeSymbology: 'نوع الباركود',
    barcodeValue: 'قيمة الباركود',
    showText: 'إظهار النص أسفل الرمز',
    barcodeDesc: 'مولد الباركود والرموز عبر الويب الأكثر قدرة في العالم. يدعم كافة التنسيقات العالمية للمنتجات والتجارة الدولية.'
  },
  en: {
    title: 'Global Barcode Platform',
    subtitle: "The world's most capable free web-based online barcode generator and QR Code generator.",
    qrTool: 'Advanced QR Generator',
    barcodeTool: 'Online Barcode Generator',
    selectTool: 'Select Desired Service',
    link: 'Link (URL)',
    text: 'Text',
    wifi: 'Wi-Fi',
    email: 'Email',
    call: 'Call',
    sms: 'SMS',
    vcard: 'V-Card',
    data: 'Code Data',
    design: 'Design Customization',
    fgColor: 'QR Color',
    bgColor: 'Background Color',
    removeMargin: 'Remove White Border',
    downloadQuality: 'Download Quality',
    downloadBtn: 'Download (PNG)',
    placeholderUrl: 'https://example.com',
    placeholderText: 'Type your text here...',
    placeholderPhone: '+123456789',
    ssid: 'Network Name (SSID)',
    password: 'Password',
    encryption: 'Encryption',
    subject: 'Subject',
    body: 'Message Body',
    firstName: 'First Name',
    lastName: 'Last Name',
    org: 'Organization',
    low: 'Low (512px)',
    high: 'High (1024px)',
    ultra: 'Ultra (2048px)',
    max: 'Max (4096px)',
    livePreview: 'Live Preview',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    barcodeSymbology: 'Barcode Type',
    barcodeValue: 'Barcode Value',
    showText: 'Show text below barcode',
    barcodeDesc: 'Download symbols of all major symbologies including EAN, UPC, QR Code, Micro QR Code, Han Xin Code, DotCode, Ultracode, ISBN, GS1-128, Code 39, Code 93, Data Matrix and more.'
  }
};

export const BARCODE_SYMBOLOGIES = [
  { value: 'ean13', label: 'EAN-13' },
  { value: 'upca', label: 'UPC-A' },
  { value: 'code128', label: 'Code 128' },
  { value: 'code39', label: 'Code 39' },
  { value: 'datamatrix', label: 'Data Matrix' },
  { value: 'gs1-128', label: 'GS1-128' },
  { value: 'itf14', label: 'ITF-14' },
  { value: 'pdf417', label: 'PDF417' },
  { value: 'azteccode', label: 'Aztec' },
  { value: 'pharmacode', label: 'Pharmacode' },
  { value: 'isbn', label: 'ISBN' },
  { value: 'issn', label: 'ISSN' },
  { value: 'qr-code', label: 'QR Code (Std)' }
];
